version: '3'

services:
  db:
    image: postgres # busca imagem do registry
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432 # porta externa será add automaticamente
    networks: 
      - backend-network
  app:
    build:
      context: ./rails_app
      dockerfile: Dockerfile
    environment: 
      - RAILS_ENV=development
    volumes:
      - ./rails_app:/rails_app
    links:
      - db # host in archive database.yml
    depends_on:
      - db
    networks: 
      - backend-network
      - frontend-network
    stdin_open: true
    tty: true
    command:
      - /bin/sh
      - -c
      - |
        rm -rf tmp/pids
        bundle exec rake db:prepare
        bundle exec rails server -b 0.0.0.0 -p 3000
  web:
    build: ./nginx # Encontra o arquivo Dockerfile automaticamente
    links:
      - app
    depends_on:
      - app
    ports:
      - 80:80
    networks: 
      - frontend-network

networks:
  frontend-network:
  backend-network: